spring:
 datasource:
     url: jdbc:sqlserver://azureservere.database.windows.net:1433;database=azure3;user=sonali@azureservere;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
     username: sonali
     password: Son@li1205mindtree
 jpa:
   show-sql: true
   hibernate:
       ddl-auto: update
       dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9191       
       
       
           